[package]
name = "api-sec-sensor-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
api-sec-sensor = { path = ".." }

[[bin]]
name = "fuzz_http1"
path = "fuzz_targets/fuzz_http1.rs"
test = false
doc = false

[[bin]]
name = "fuzz_http2"
path = "fuzz_targets/fuzz_http2.rs"
test = false
doc = false

[[bin]]
name = "fuzz_quic"
path = "fuzz_targets/fuzz_quic.rs"
test = false
doc = false

[[bin]]
name = "fuzz_websocket"
path = "fuzz_targets/fuzz_websocket.rs"
test = false
doc = false

[[bin]]
name = "fuzz_grpc"
path = "fuzz_targets/fuzz_grpc.rs"
test = false
doc = false

[[bin]]
name = "fuzz_redaction"
path = "fuzz_targets/fuzz_redaction.rs"
test = false
doc = false

[workspace]
members = ["."]
