apiVersion: v1
kind: ConfigMap
metadata:
  name: api-sentinel-sensor
  labels:
    app.kubernetes.io/name: api-sentinel-sensor
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config.toml: |
    [sensor]
    bpf = {{ .Values.sensor.bpfObjectPath | quote }}
    ingest = {{ .Values.sensor.ingestUrl | quote }}
    account_id = {{ .Values.sensor.accountId }}
    batch_size = {{ .Values.sensor.batchSize }}
    role = {{ .Values.sensor.role | quote }}
    max_buffer_bytes = {{ .Values.sensor.maxBufferBytes }}
    max_total_buffer_bytes = {{ .Values.sensor.maxTotalBufferBytes }}
    metrics_port = {{ .Values.sensor.metricsPort }}
    sample_default = {{ .Values.sensor.sampleDefault }}
    sample_health = {{ .Values.sensor.sampleHealth }}
    discover_libs = true
